[tool.robotpy]
robotpy_version = "2025.2.1.3"
requires = [
  "robotpy-commands-v2",
  "robotpy-rev",
  "robotpy-navx",
  "robotpy-pathplannerlib",
  "photonlibpy",
  "numpy==2.2.1.dev0; platform_machine == 'roborio'"
]
