name: PyFRC Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code from target branch
      uses: actions/checkout@v4
    - name: Set up Python 3.x environment
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Update, install and sync robotpy and project dependencies
      run: |
        python -m pip install --upgrade pip
        python ./scripts/update.py
        python ./scripts/install.py
        python ./scripts/sync.py
    - name: Wait for installation to finalize
      uses: GuillaumeFalourd/wait-sleep-action@v1
      with:
        time: "30"
    - name: Run PyFRC tests
      run: |
        python ./scripts/test.py